# Generated by Django 5.1.2 on 2025-01-10 01:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_send_at', models.DateTimeField(default=datetime.datetime(2025, 1, 10, 1, 18, 53, 494173), verbose_name='Date and time to send')),
                ('finish_send_at', models.DateTimeField(default=datetime.datetime(2025, 1, 10, 1, 18, 53, 494206), verbose_name='Date and time to finish')),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('created', 'Created'), ('running', 'Running')], default='created', max_length=9, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Mailing',
                'verbose_name_plural': 'Mailings',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MailingAttempts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(verbose_name='Date and time of attempt')),
                ('status', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=8, verbose_name='Status')),
                ('mail_server_response', models.TextField(blank=True, null=True, verbose_name='Server response')),
            ],
            options={
                'verbose_name': 'Mailing attempt',
                'verbose_name_plural': 'Mailing attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Text message')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Recipient email')),
                ('name', models.CharField(max_length=255, verbose_name='Recipient name')),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Comment')),
            ],
            options={
                'verbose_name': 'Recipient',
                'verbose_name_plural': 'Recipients',
                'ordering': ['id'],
            },
        ),
    ]
