# Generated by Django 5.1.2 on 2025-01-09 01:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 1, 25, 42, 192223), verbose_name='Date and time to finish'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 9, 1, 25, 42, 192181), verbose_name='Date and time to send'),
        ),
    ]
