# Generated by Django 5.1.2 on 2025-01-10 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_finish_send_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 1, 20, 34, 935303), verbose_name='Date and time to finish'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 10, 1, 20, 34, 935271), verbose_name='Date and time to send'),
        ),
    ]
