# Generated by Django 5.1.2 on 2025-01-12 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_options_mailing_is_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 2, 27, 37, 204060), verbose_name='Date and time to finish'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 12, 2, 27, 37, 204032), verbose_name='Date and time to send'),
        ),
    ]
