# Generated by Django 5.1.2 on 2025-01-22 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_alter_mailing_finish_send_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='finish_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 19, 42, 38, 940765), verbose_name='Date and time to finish'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='first_send_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 22, 19, 42, 38, 940733), verbose_name='Date and time to start'),
        ),
        migrations.AlterField(
            model_name='mailingattempts',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], default='SUCCESS', max_length=8, verbose_name='Status'),
        ),
    ]
